site_name: titan
theme:
  name: readthedocs
  use_pygments: true
  palette:
    primary: deep orange
    accent: orange
  features:
    - navigation.instant
    - search.suggest

plugins:
  - search:
      min_search_length: 2

extra_css:
  - css/extra.css

repo_url: https://github.com/devOpifex/titan/
repo_name: Github
site_description: Serve Prometheus metrics for shiny applications and plumber services
site_author: Opifex
copyright: Opifex
google_analytics: ['G-TZMQ98HS6D', 'titan.opifex.org']

markdown_extensions:
    - admonition
    - smarty
    - toc:
        permalink: True
        separator: "-"

nav:
  - Home: index.md
  - About:
    - Monitoring: about.md
    - Internals: internals.md
  - Guide: 
      - Installation: guide/installation.md
      - Metrics: guide/metrics.md
      - Shiny: guide/shiny.md
      - Plumber: guide/plumber.md
      - Ambiorix: guide/ambiorix.md
      - Authentication: guide/authentication.md
  - Deploy:
    - Prometheus: deploy/prometheus.md
    - Grafana: deploy/grafana.md
  - Meta:
    - Contribute: meta/contribute.md
    - Changelog: meta/changelog.md
